const Standart_room = [
{
	id:1,
	roomprice:60,
	imgsrc:"/images/standard_room.jpeg", 
	hoteTitle:"Standart Economic Single Room",
	textC:"Ah, the humble studio apartment. At one time, this dwelling was considered to...",
	user:"2",
	bell:"2", 
	chart:"3",
},
{
	id:2,
	roomprice:50,
	imgsrc:"/images/standard_room1.jpeg", 
	hoteTitle:"Standart Double Room",
	textC:"Economy Single Room is well-furnished guest rooms 11 square meters with the m...",
	user:"1",
	bell:"5", 
	chart:"160",
},
{
	id:3,
	roomprice:10,
	imgsrc:"/images/standard_room2.jpg",
	hoteTitle:'Standart One Person Room',
	textC:"Classic Rooms in the our Hotel have been refurbished to a very high standard....",
	user:"3",
	bell:"1", 
	chart:"96",
},
{
	id:4,
	roomprice:30,
	imgsrc:"/images/standard_room4.jpeg",
	hoteTitle:'Standart Economic Double Room',
	textC:"Classic Rooms in the our Hotel have been refurbished to a very high standard....",
	user:"3",
	bell:"1", 
	chart:"96",
},
{
	id:5,
	roomprice:25,
	imgsrc:"/images/standard_room5.jpeg",
	hoteTitle:'Standart Big Room',
	textC:"Classic Rooms in the our Hotel have been refurbished to a very high standard....",
	user:"3",
	bell:"1", 
	chart:"96",
},
{
	id:6,
	roomprice:10,
	imgsrc:"/images/standard_room6.jpeg",
	hoteTitle:'Standart Blue Room',
	textC:"Classic Rooms in the our Hotel have been refurbished to a very high standard....",
	user:"3",
	bell:"1", 
	chart:"96",
},
]


export default Standart_room;
